SELECT aa.REMARK as 异常类型, aa.REAL_NAME as 姓名, aa.PHONE as 手机号码 FROM (
--导入后未激活临时店经状态<>-1，或者未激活已经为店经
SELECT '1-未激活<>-1 OR =店经' REMARK, 
       B.REAL_NAME,
       B.PHONE,
       B.LOGIN_FIRST_DATA_TIME,
       B.FIRST_LOGIN_APP_DATE,
       B.IS_TEMP_SUPER_CUSTOMER,
       ACTIVATED_TIME,
       EXPIRE_DATE,
       A.ACTUALLY_ACTIVATED_TIME,
       C.LEVEL_NAME
  FROM DM_ROMA_SUPER_CUSTOMER_RECORD A
  JOIN DM_BLC_CUSTOMER B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
  JOIN DM_ROMA_USER_LEVEL_NEW C
    ON B.USER_LEVEL_NEW_ID = C.ID
 WHERE (ACTUALLY_ACTIVATED_TIME IS NULL AND IS_TEMP_SUPER_CUSTOMER <> -1)
    OR (LEVEL_NAME LIKE '%店经' AND IS_TEMP_SUPER_CUSTOMER = -1)

UNION ALL

--2.导入后激活，结束日期大于当天的，临时店经状态仍为0,-1的或者已经达标转正，但状态仍不为店经
SELECT '2-激活仍为0，-1' REMARK,
       B.REAL_NAME,
       B.PHONE,
       B.LOGIN_FIRST_DATA_TIME,
       B.FIRST_LOGIN_APP_DATE,
       B.IS_TEMP_SUPER_CUSTOMER,
       ACTIVATED_TIME,
       EXPIRE_DATE,
       A.ACTUALLY_ACTIVATED_TIME,
       C.LEVEL_NAME
  FROM DM_ROMA_SUPER_CUSTOMER_RECORD A
  JOIN DM_BLC_CUSTOMER B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
  JOIN DM_ROMA_USER_LEVEL_NEW C
    ON B.USER_LEVEL_NEW_ID = C.ID
 WHERE (EXPIRE_DATE > TRUNC(SYSDATE) AND IS_TEMP_SUPER_CUSTOMER IN (0, -1))
    OR (LEVEL_NAME NOT LIKE '%店经' AND IS_TEMP_SUPER_CUSTOMER = 2)
    
UNION ALL
--3未达标，但是临时店经状态已经是2
SELECT '3-未达标状态是2' REMARK,
       B.REAL_NAME,
       B.PHONE,
       B.LOGIN_FIRST_DATA_TIME,
       B.FIRST_LOGIN_APP_DATE,
       B.IS_TEMP_SUPER_CUSTOMER,
       ACTIVATED_TIME,
       EXPIRE_DATE,
       A.ACTUALLY_ACTIVATED_TIME,
       C.LEVEL_NAME
  FROM DM_ROMA_SUPER_CUSTOMER_RECORD A
  JOIN DM_BLC_CUSTOMER B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
  JOIN DM_ROMA_USER_LEVEL_NEW C
    ON B.USER_LEVEL_NEW_ID = C.ID
 WHERE STATUS <> 'PASSED'
   AND IS_TEMP_SUPER_CUSTOMER = 2
   AND EXPIRE_DATE > TRUNC(SYSDATE)
   AND ACTIVATED_TIME < TRUNC(SYSDATE)

UNION ALL
--4-埋点有记录却没首次登陆时间
SELECT '4-埋点有首登无' REMARK,
       B.REAL_NAME,
       B.PHONE,
       B.LOGIN_FIRST_DATA_TIME,
       B.FIRST_LOGIN_APP_DATE,
       B.IS_TEMP_SUPER_CUSTOMER,
       ACTIVATED_TIME,
       EXPIRE_DATE,
       A.ACTUALLY_ACTIVATED_TIME,
       C.LEVEL_NAME
  FROM DM_ROMA_SUPER_CUSTOMER_RECORD A
  JOIN DM_BLC_CUSTOMER B
    ON A.CUSTOMER_ID = B.CUSTOMER_ID
  JOIN DM_ROMA_USER_LEVEL_NEW C
    ON B.USER_LEVEL_NEW_ID = C.ID
 WHERE ACTUALLY_ACTIVATED_TIME IS NULL
   AND EXISTS (SELECT 1
          FROM DM_LOG_MAIDIAN_LOGIN D
         WHERE D.CUSTOMER_ID = B.CUSTOMER_ID
           AND A.IMPORT_TIME < D.OPERATE_TIME)
) aa