SELECT F.DT, F.UV, F.PV, R.SALE_MONEY as 销售额
  FROM DW_FLOWS_LOG_MAIDIAN_DAY F
  LEFT JOIN RPT_SALE_ORDER_SUM R
    ON F.DT = R.DT
 WHERE F.DT > (SYSDATE - 31)
   AND F.USER_TYPE IS NULL
   AND F.TARGET_TYPE IS NULL
   AND F.EVENT_ID IS NULL